export const CONFIG = {
  DB_PROVIDER: 'DB_PROVIDER',
  ETHEREUM_ENDPOINT: 'ETHEREUM_ENDPOINT',
  SYNC_SERVICE_OPTIONS: 'SYNC_SERVICE_OPTIONS',
  OPERATOR_OPTIONS: 'OPERATOR_OPTIONS',
  CONTRACT_OPTIONS: 'CONTRACT_OPTIONS',
  EVENT_WATCHER_OPTIONS: 'EVENT_WATCHER_OPTIONS',
}

export const DB_PREFIXES = {
  TRANSACTIONS: '00',
  BLOCK_HEADERS: '01',
  PREDICATES: '02',
  DEPOSITS: '03',
  EXITS: '04',
  ACCOUNTS: '05',
  KEYSTORES: '06',
  EXITABLE_ENDS: '07',
  FINALIZED_EXITS: '08',
  EXITED_RANGES: '09',
  FAILED_TRANSACTION_IMPORTS: '10',
  SEEN_EVENTS: '11',
  LATEST_BLOCK: '12',
  LATEST_STATE: '13',
  LAST_LOGGED_BLOCK: '14',
  LAST_SYNCED_BLOCK: '15',
}
